openapi: 3.1.0
info:
  title: Demo API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  '/version':
    get:
      summary: Get current version
      operationId: getVersion
      responses:
        200:
          description: Successful response
#          content:
#            application/json:
              # schema:
              #   type: array
              #   items:
              #     $ref: '#/components/schemas/test-page-url'
# components:
#   schemas:
#     test-page-url:
#       type: object
#       properties:
#         url:
#           type: string
#           example: 'https://example.com/'
#           description: URL of the test page
#         description:
#           type: string
#           example: 'Page for testing...'
#           description: Description of the test page
