version: '3.8'
name: merchant-portal-backend-dev
services:
  php:
    build:
      context: ../.
      dockerfile: ./.docker/Dockerfile
      target: php_dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    image: rncb-ecom/${COMPOSE_PROJECT_NAME}-php
    restart: unless-stopped
    volumes:
      - ../.:/var/www/html/
  webserver:
    configs:
      - source: nginx_conf
        target: /etc/nginx/templates/default.conf.template
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    env_file: ${APP_ENV_FILE:-./.env.app.dist}
    environment:
      - APP_PORT=${APP_PORT:-80}
    image: nginx:1.24-alpine
    ports:
      - target: 80
        published: ${APP_PORT:-80}
        protocol: tcp
    restart: unless-stopped
  sqldb:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
      POSTGRES_USER_FILE: /run/secrets/db_user
    image: postgres:14-alpine
    restart: unless-stopped
    secrets:
      - db_name
      - db_passwd
      - db_user
    volumes:
      - pgdata:/var/lib/postgresql/data/
configs:
  nginx_conf:
    file: ./nginx/default.conf.template
secrets:
  db_name:
    file: ../.secrets/db-name
  db_passwd:
    file: ../.secrets/db-passwd
  db_user:
    file: ../.secrets/db-user
volumes:
  pgdata: