version: '3.8'
name: merchant-portal-backend-dev
services:
  php:
    build:
      context: ../.
      dockerfile: ./.docker/Dockerfile
      target: php_dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    image: rncb-ecom/${COMPOSE_PROJECT_NAME}-php
    restart: unless-stopped
    volumes:
      - ../.:/var/www/html/
  webserver:
    configs:
      - source: nginx_conf
        target: /etc/nginx/templates/default.conf.template
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      - APP_HOST=${APP_HOST:?}
      - APP_PORT=${APP_PORT:-80}
    image: nginx:1.24-alpine
    ports:
      - target: 80
        published: ${APP_PORT:-80}
        protocol: tcp
    restart: unless-stopped
  sqldb:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_USER: ${DB_USER:?}
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ../.local/pgdata/:/var/lib/postgresql/data/
  build-api:
    build: ./.docker/openapi/
    command: ["openapi-generator-cli", "generate"]
    image: ecom-rncb/openapi-generator
    profiles:
      - build-api
    volumes:
      - ../.:/app/
configs:
  nginx_conf:
    file: ./nginx/default.conf.template
